config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show] do
    post 'downgrade' => 'users#downgrade', as: :downgrade 
  end
  resources :wikis do 
      resources :collaborations, only: [:create, :destroy]
      resources :references, only: [:create, :destroy]
  end
  get 'wikis/create_wiki_from_link/:link_id' => 'wikis#create_wiki_from_link', :as => 'create_wiki_from_link'

  resources :links
  post 'create_link_with_wiki' => "links#create_link_with_wiki", :as => "create_link_with_wiki"

  resources :charges, only: [:new, :create]
  root to: 'welcome#index'
  get '/help', to: 'welcome#help'

  resources :tags, only: [:show, :index]

  get "connect" => "links#connect_to_pocket", :as => "connect_to_pocket"
  get "authorize_callback" => "links#authorize_callback", :as => "authorize_callback"

  get "/fetch_tab/:id" => 'users#selected_tab', as: 'fetch_tab', format: 'js'
end

app/models/user.rb
class User < ActiveRecord::Base

  extend FriendlyId
  friendly_id :username, use: :slugged
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  has_many :collaborations
  has_many :wikis
  has_many :shared_wikis, through: :collaborations, source: :wiki
  has_many :links

  validates :username, presence: true, uniqueness: true

  scope :all_except, -> (user){ where.not(id: user) }
  scope :exclude_collaborators, -> (wiki){where.not(id: wiki.users)}

  after_initialize :init

  def admin?
    role == 'admin'
  end

  def premium?
    role == 'premium'
  end

  def standard?
    role == 'standard'
  end

  def is_owner_of?(wiki)
    admin? || wiki.user == self || wiki.new_record?
  end

  def init
    self.role ||= 'standard'
  end

  def upgrade
    self.update_attribute(:role, 'premium')
  end

  def downgrade
    private_wikis = self.wikis.only_private
    private_wikis.each { |wiki| wiki.make_public }
    self.update_attribute(:role, 'standard')
  end

  def pocket_authorized?
    return !PocketApi.access_token.nil?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: :show

  def show
    @user = User.friendly.find(params[:id])
    authorized_wikis = policy_scope(Wiki)
    @user_wikis = authorized_wikis.select{ |w| @user.is_owner_of?(w) }.paginate(page: params[:page], per_page: 5)
    # @shared_wikis = authorized_wikis.select { |w| w.is_owned_by?(@user) }.paginate(page: params[:page], per_page: 5)
    # @links = @user.links.paginate(page: params[:page], per_page: 5)
    @active_tab = params[:tab] || "my-wikis"
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
    else
      flash[:error] = "Invalid user information"
    end
    redirect_to edit_user_registration_path
  end

  def downgrade
    current_user.downgrade
    redirect_to user_path(current_user)
  end

  def selected_tab
    puts params[:tab]
    @user = User.friendly.find(params[:id])
    if params[:tab] == "my-wikis"
      authorized_wikis = policy_scope(Wiki)
      @tab_content = authorized_wikis.select{ |w| @user.is_owner_of?(w) }.paginate(page: params[:page], per_page: 5)
    elsif params[:tab] == "shared-wikis"
      authorized_wikis = policy_scope(Wiki)
      @tab_content = authorized_wikis.select { |w| w.is_owned_by?(@user) }.paginate(page: params[:page], per_page: 5)
    elsif params[:tab] == "my-links"
      @tab_content = @user.links.paginate(page: params[:page], per_page: 5)
    end
    @active_tab = params[:tab]
    respond_to do |format|
        format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_controls.html.erb
<div class="user-controls wp-collapse wp-block">
  <ul class="user-links">
    <% if user_signed_in? %>
      <li><%= link_to "New Wiki", new_wiki_path, class: 'btn btn-info' %></li>
      <li><%= link_to "New Link", new_link_path, class: 'btn btn-warning' %></li>
    <% end %>
  </ul>
  <div class="search-form">
    <%= form_tag wikis_path, method: :get do %>
      <div class="sidebar-form-group">
        <%= text_field_tag :search, params[:search], class: 'form-field', autocomplete: :off %>
      </div>
      <div class="sidebar-form-group">
        <%= submit_tag "Search Wikis", class: 'wp-button' %>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div class="search-form">
      <%= form_tag links_path, method: :get do %>
        <div class="sidebar-form-group">
          <%= text_field_tag :search, params[:search], class: 'form-field', autocomplete: :off %>
        </div>
        <div class="sidebar-form-group">
          <%= submit_tag "Search Links", class: 'wp-button' %>
        </div>
      <% end %>
    </div>
    <%if current_user.pocket_authorized? %>
      <div class="search-form">
        <p>Search your Pocket account for saved links.</p>
        <%= form_tag links_path, method: :get do %>
          <div class="sidebar-form-group">
            <%= text_field_tag :pocket_search, params[:pocket_search], class: 'form-field', autocomplete: :off %>
          </div>
          <div class="sidebar-form-group">
            <%= submit_tag "Search Pocket for Links", class: 'wp-button' %>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="authorize-pocket sidebar-form-group">
        <%= button_to "Authorize your Pocket Account", connect_to_pocket_path, class: 'wp-button', method: 'get' %>
      </div>
    <% end %>
  <% end %>
  <div class="search-form">
    <%= form_tag tags_path, method: :get do %>
      <div class="sidebar-form-group">
        <%= text_field_tag :tag_search, params[:tag_search], class: 'form-field', autocomplete: :off %>
      </div>
      <div class="sidebar-form-group">
        <%= submit_tag "Search Tags", class: 'wp-button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <% if user_signed_in? && user == current_user %>
        <h4><%= user.username %> Info <%= link_to "Edit", edit_user_registration_path(user), class: 'btn btn-sm btn-success' %></h4>
    <% else %>
      <h4><%= user.username %> Info</h4>
    <% end %>
  </div>
  <div class="panel-body">
    <p>Email: <%= user.email %></p>
    <p>Account Type: <%= user.role.capitalize %></p>
    <p>Wikis: <%= user.wikis.count %></p>
    <p>Shared Wikis: <%= user.shared_wikis.count %></p>
  </div>
</div>

app/views/users/selected_tab.js.erb
console.log('selected_tab.js');
$(".selected-tab").removeClass('selected-tab');
<% if @active_tab == 'my-links' %>
  $("#selected-list").html("<%= escape_javascript(render partial: 'links/link_list', locals: { links: @tab_content } ) %>"); 
  $("#my-links").addClass('selected-tab');
<% else%>
  $("#selected-list").html("<%= escape_javascript(render partial: 'wikis/wiki_list', locals: { wikis: @tab_content } ) %>"); 
  <% if @active_tab == 'my-wikis' %>
    $("#my-wikis").addClass('selected-tab');
  <% else %>
    $("#shared-wikis").addClass('selected-tab');
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="paginated-content">
  <%= render partial: 'users/user', locals: {user: @user} %>
  <div class="profile-tab-group">
    <%= link_to "#{@user.username}'s Wikis", fetch_tab_path(@user, tab: 'my-wikis'), :remote => true, class: 'profile-tab selected-tab', id: 'my-wikis' %>
    <%= link_to "Shared Wikis", fetch_tab_path(@user, tab: 'shared-wikis'), :remote => true, class: 'profile-tab', id: 'shared-wikis' %>
    <%= link_to "#{@user.username}'s Links", fetch_tab_path(@user, tab: 'my-links'), :remote => true, class: 'profile-tab', id: 'my-links'  %>
  </div>
  <div id="selected-list">
    <%= render partial: 'wikis/wiki_list', locals: {wikis: @user_wikis} %>
  </div>
</div>