config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show] do
    post 'downgrade' => 'users#downgrade', as: :downgrade 
  end
  resources :wikis do 
      resources :collaborations, only: [:create, :destroy]
      resources :references, only: [:create, :destroy]
  end
  get 'wikis/create_wiki_from_link/:link_id' => 'wikis#create_wiki_from_link', :as => 'create_wiki_from_link'

  resources :links
  post 'create_link_with_wiki' => "links#create_link_with_wiki", :as => "create_link_with_wiki"

  resources :charges, only: [:new, :create]
  root to: 'welcome#index'
  get '/help', to: 'welcome#help'

  resources :tags, only: [:show, :index]

  get "connect" => "links#connect_to_pocket", :as => "connect_to_pocket"
  get "authorize_callback" => "links#authorize_callback", :as => "authorize_callback"

  get "/fetch_tab/:id" => 'users#selected_tab', as: 'fetch_tab', format: 'js'
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :references
  has_many :wikis, through: :references

  acts_as_taggable

  def self.search(query)
    search_tags = query.split(' ')
    tag_matched_links = Link.tagged_with(search_tags, :any => true)
    title_matched_links = Link.where("title LIKE ?", "%#{query}%")
    url_matched_links = Link.where("url LIKE ?", "%#{query}%")
    return tag_matched_links + title_matched_links + url_matched_links
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    if params[:pocket_search]
      @links = []
      @retrieved_links = PocketApi.retrieve({:search => params[:pocket_search], :sort => 'title'})
      @retrieved_links.each do |link_hash, retrieved_link|
        new_link = Link.new(
          user: current_user,
          title: retrieved_link["given_title"],
          url: retrieved_link["given_url"]
        )
        if new_link.title.nil? || new_link.title == ""
          new_link.title = retrieved_link["resolved_title"]
        end
        if new_link.url.nil? || new_link.url == ""
          new_link.url = retrieved_link["resolved_url"]
        end
        @links << new_link
      end
    elsif params[:search]
      @links = Link.search(params[:search])
    else
      @links = Link.all
    end
  end

  def new
    @link = Link.new
    authorize @link
  end

  def create
    @link = current_user.links.build(link_params)
    authorize @link
    if @link.save
      flash[:notice] = "Link saved succesfully."
      redirect_to @link
    else
      flash[:error] = "There was an error saving link. Please try again."
      render :new
    end
  end

  def create_link_with_wiki
    @link = current_user.links.build(link_params)
    authorize @link
    if @link.save
      @wiki = current_user.wikis.build(
        title: @link.title,
        body: "[#{@link.title}](#{@link.url})"
      )
      @wiki.save
      @reference = @wiki.references.build(link: @link)
      @reference.save
      flash[:notice] = "Wiki created and link saved succesfully."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "There was an error saving link. Please try again."
      render :index
    end
  end

  def show
    @link = Link.find(params[:id])
    authorize @link
    linked_wikis = @link.wikis
    @wikis = linked_wikis.select { |w| policy(w).show? }.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @link = Link.find(params[:id])
    authorize @link
  end

  def update
    @link = Link.find(params[:id])
    authorize @link
    if @link.update_attributes(link_params)
      flash[:notice] = "Link edited succesfully."
      redirect_to @link
    else
      flash[:error] = "There was an error editing link. Please try again."
      render :edit
    end
  end

  def destroy
    @link = Link.find(params[:id])
    authorize @link
    if @link.destroy
      flash[:alert] = "Link, \"#{@link.title}\" deleted succesfully."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error deleting link. Please try again."
      render :show
    end
  end

  def connect_to_pocket
    PocketApi::Connection.client_key = ENV["POCKET_CONSUMER_KEY"]
    redirect_to PocketApi::Connection.generate_authorize_url(ENV["AUTHORIZATION_CALLBACK_URL"])
  end

  def authorize_callback
    @token = PocketApi::Connection.generate_access_token
    session[:access_token_hash] = {current_user.id => @token}
    PocketApi.configure(client_key: ENV["POCKET_CONSUMER_KEY"], access_token: session[:access_token_hash][current_user.id])
    redirect_to links_path
  end

  private

  def link_params
    params.require(:link).permit(:title, :url, :tag_list)
  end

end

app/views/links/_controls.html.erb
<ul class="link-controls">
  <li>
    <%= link_to link.user.username, user_path(link.user), class: 'btn btn-sm btn-info' %>
  </li>
  <li>
    <% if policy(link).edit? %>
      <%= link_to "Edit", edit_link_path(link), class: 'btn btn-sm btn-success' %>
    <% end %>
  </li>
  <li>
    <% if policy(link).destroy? %>
      <%= link_to "Delete", link, method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Are you sure you want to delete this link?' } %> 
    <% end %>
  </li>
</ul>

app/views/links/_form.html.erb
<%= form_for link do |f| %>
  <div class="form-group">
    <%= f.submit "Save", class: 'wp-button' %>
  </div><br>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', autofocus: true, autocomplete: :off %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.url_field :url, class: 'form-control', autocomplete: :off %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list, "Tags (separated by commas)" %>
    <%= f.text_field :tag_list, value: link.tag_list.to_s, class: 'form-control', autocomplete: :off %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div class="excerpt-panel">
  <div class="excerpt-header">
    <% if link.new_record? %>
      <h4><%= link.title %></h4>
    <% else %>
      <h4><%= link_to link.title, link_path(link) %></h4>
    <% end %>
  </div>
  <div class="excerpt-controls">
    <%= render partial: 'links/controls', locals: {link: link} %>
  </div>
  <div class="excerpt-content">
    <p>Url: <%= link_to link.url, link.url, target: '_blank' %></p>
    <ul class="link-info">
      <li>User: <%= link.user.username %></li>
      <li>Wikis: <%= link.wikis.count %></li>
      <li>Tags: <%= tags_to_links(link.tag_list) %></li>
    </uL>
    <% if link.new_record? %>
      <%= form_for Link.new, :url => create_link_with_wiki_path do |f| %>
        <%= f.hidden_field :title, value: link.title %>
        <%= f.hidden_field :url, value: link.url %>
        <%= f.hidden_field :user, value: current_user %>
        <%= f.submit "Create a New Wiki with this Link." %>
      <% end %>
    <% else %>
      <%= link_to "Create a New Wiki with this Link.", create_wiki_from_link_path(link) %>
    <% end %>
  </div>
</div>

app/views/links/_link_list.html.erb
<% links.each do |link| %>
  <p>
    <%= render partial: 'links/link', locals: {link: link} %>
  </p>
<% end %>
<%= will_paginate links %>

app/views/links/_reference_link.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <%= form_for [wiki, reference] do |f| %>
      <p>
        <%= f.submit "Add", class: 'btn btn-xs btn-success' %>
        <%= link.title %>: <%= link_to link.url, link.url %>
        <%= f.hidden_field :link_id, value: link.id %>
      </p>
      <small>Tags: <%= tags_to_links(link.tag_list) %></small>
    <% end %>
  </div>
</div>

app/views/links/edit.html.erb
<div class="col-md-8">
  <h1>Edit Link</h1>
  <%= render partial: 'links/form', locals: {link: @link} %>
</div>

app/views/links/index.html.erb
<div class="paginated-content">
  <% @links.each do |link| %>
    <p>
      <%= render partial: 'links/link', locals: {link: link} %>
    </p>
  <% end %>
</div>

app/views/links/new.html.erb
<div class="static-content">
  <h1>New Link</h1>
  <%= render partial: 'links/form', locals: {link: @link} %>
</div>

app/views/links/show.html.erb
<div class="col-md-8">
  <%= render partial: 'links/link', locals: {link: @link} %>
  <h1><%= @link.title %>'s Wikis</h1>
  <% @wikis.each do |wiki| %>
    <%= render partial: 'wikis/excerpt', locals: {wiki: wiki} %>
  <% end %>
  <%= will_paginate @wikis %>
</div>