config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show] do
    post 'downgrade' => 'users#downgrade', as: :downgrade 
  end
  resources :wikis do 
      resources :collaborations, only: [:create, :destroy]
      resources :references, only: [:create, :destroy]
  end
  get 'wikis/create_wiki_from_link/:link_id' => 'wikis#create_wiki_from_link', :as => 'create_wiki_from_link'

  resources :links
  post 'create_link_with_wiki' => "links#create_link_with_wiki", :as => "create_link_with_wiki"

  resources :charges, only: [:new, :create]
  root to: 'welcome#index'
  get '/help', to: 'welcome#help'

  resources :tags, only: [:show, :index]

  get "connect" => "links#connect_to_pocket", :as => "connect_to_pocket"
  get "authorize_callback" => "links#authorize_callback", :as => "authorize_callback"

  get "/fetch_tab/:id" => 'users#selected_tab', as: 'fetch_tab', format: 'js'
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @stripe_btn_data = {
      key: "#{Rails.configuration.stripe[:publishable_key]}",
      description: "Wiki Pocket Premium Account Upgrade - #{current_user.username}",
      amount: Amount.default,
      email: current_user.email
    }
  end

  def create

    # Create Stripe Customer object
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    #Create a Stripe Charge object
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Wiki Pocket Premium Account Upgrade - #{current_user.email}",
      currency: 'usd'
    )

    current_user.upgrade
    flash[:success] = "Thanks for your payment, #{current_user.email}!"
    redirect_to user_path(current_user)

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end

  class Amount
    def self.default
      return 15_00
    end
  end



end

app/views/charges/_downgrade.html.erb
<h2>Want to downgrade to a standard account?</h2>
<p>When you downgrade from premium to standard, any private wikis you created will be converted into public wikis automatically.</p>
<p>You will also no longer be able to create, edit and delete private wikis that have been shared with you by other users.</p>

<%= link_to "Yes, downgrade my account.", user_downgrade_path(current_user), class: 'btn btn-danger', method: :post, data: {confirm: "Are you sure?"} %>

app/views/charges/_upgrade.html.erb
<h2>Want to upgrade to a premium account?</h2>
<%= form_tag charges_path do %>
  <h4>For $15 USD your account will be upgraded to a premium acount.</h4>
  <script class="stripe-button" src="https://checkout.stripe.com/checkout.js" data-key="<%= stripe_btn_data[:key] %>" data-amount=<%= stripe_btn_data[:amount] %> data-description="<%= stripe_btn_data[:description] %>" data-email="<%= stripe_btn_data[:email] %>" ></script>
<% end %>

app/views/charges/new.html.erb
<div class="col-md-8">
  <% if current_user.standard? %>
    <%= render partial: 'charges/upgrade', locals: {stripe_btn_data: @stripe_btn_data} %>
  <% elsif current_user.premium? %>
    <%= render 'downgrade' %>
  <% end %>
</div>
<div class="col-md-4">
  <h2>Premium Accounts can:</h2>
  <ul>
    <li>Create private wikis</li>
    <li>Add collaborators to your private wikis.</li>
    <li>Edit your private wikis or wikis shared with you.</li>
  </ul>
  <h2>Standard Accounts can:</h2>
  <ul>
    <li>Create public wikis.</li>
    <li>Edit any public wiki.</li>
  </ul>
  <%= render 'users/user', locals: {user: current_user} %>
</div>