config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show] do
    post 'downgrade' => 'users#downgrade', as: :downgrade 
  end
  resources :wikis do 
      resources :collaborations, only: [:create, :destroy]
      resources :references, only: [:create, :destroy]
  end
  get 'wikis/create_wiki_from_link/:link_id' => 'wikis#create_wiki_from_link', :as => 'create_wiki_from_link'

  resources :links
  post 'create_link_with_wiki' => "links#create_link_with_wiki", :as => "create_link_with_wiki"

  resources :charges, only: [:new, :create]
  root to: 'welcome#index'
  get '/help', to: 'welcome#help'

  resources :tags, only: [:show, :index]

  get "connect" => "links#connect_to_pocket", :as => "connect_to_pocket"
  get "authorize_callback" => "links#authorize_callback", :as => "authorize_callback"

  get "/fetch_tab/:id" => 'users#selected_tab', as: 'fetch_tab', format: 'js'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wiki Pocket</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="app-header">
      <nav>
        <div class="nav-logo">
          <%= link_to (user_signed_in? ? wikis_path : root_path), class: 'logo' do %>
            <%= image_tag 'Logo@2x.png' %>
          <% end %>
        </div>
        <span class="wp-reveal"><i class="fa fa-bars"></i></span>
        <ul class="nav-left wp-collapse wp-inline-block">
          <li><%= link_to "Browse Wikis", wikis_path %></li>
          <li><%= link_to "Browse Tags", tags_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Browse Links", links_path %></li>
          <% end %>
        </ul>
        <% if flash[:notice] %>
          <div class="flash">
            <button type="button" class="close-flash" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
          <% elsif flash[:error] %>
          <div class="flash">
            <button type="button" class="close-flash" data-dismiss="alert">&times;</button>
            <%= flash[:error] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="flash">
            <button type="button" class="close-flash" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
      </nav>
    </div>
    <div class="sidebar">
      <nav>
        <ul class="nav-right wp-collapse wp-block">
          <% if user_signed_in? %>
            <li><%= link_to (current_user.username.capitalize || current_user.email), user_path(current_user) %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
          <li><%= link_to "?", help_path %></li>
        </ul>
      </nav>
      <%= render partial: 'users/controls' %>
    </div>
    <div class="main-content">
      <%= yield %>
    </div>
  </body>
</html>